name: wave_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  audioplayers: ^3.0.1
  intl: ^0.18.0
  get:
  stop_watch_timer: 
  hive:
  hive_flutter:
  orientation_widget: ^1.0.0
  sizer: ^2.0.15
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:  

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    
  #   - images/a_dot_ham.jpeg
  
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/Arialn.ttf
        
  #         style: italic
    - family: DS-Digital
      fonts:
        - asset: assets/fonts/DS-DIGIB.TTF


